spring:
  profiles:
    active: dev
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: false
    checkTemplateLocation: true
    content-type: text/html
    exposeRequestAttributes: false
    exposeSessionAttributes: false
    exposeSpringMacroHelpers: false
    prefer-file-system-access: true
    suffix: .ftl
    charset: utf-8
    template-loader-path: classpath:/templates/
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: NON_NULL
weChat:
  pay:
    appId: wxfb0967015f2c8735
    mchId: 1539515591
    mchKey: 9dc8133c841faf945fd5844823755a34
    appSecret: 9dc8133c841faf945fd5844823755a34
    notifyUrl: /pay/weChatPay/notify
    orderNamePrefix: 急速追书VIP会员-
aliPay:
  pay:
    serverPayUrl: https://openapi.alipay.com/gateway.do
    appId: 2019061065457793
    sellerId: 2088721844490506
    appPrivateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDjjml0uklnItJxPW+Nw4FSnnFsVYM//wc3iHCs3o/ONLK3ZF1VfSHvlnVWl4621ZIdEIqCJ5EmMHQktlxqGRR8YZMT0AdLEb7CmiQzPh0VmqRjL6S8uMbHasiwfZaiBSojs4ISbqUPl/iXj8NIBF2kPJ8VhdVuz1AV71o1VFIhGKABzm0MLTk9pEKTyKqkevCzgW1mhnUGjLoBbnR9NGU7jfVS+c8EI8+uLyA/f88MCtxW5goCDbKbCgtGKKaRPcO8Ah2LlSM2uHUEHphbda+N7ogRDqk0wU+4efrAEJ7cERZ+PVNr34Dy7xmDgTHFRqUFc5F8kNY6u9QgGGH2J3TJAgMBAAECggEARdJzvzJNxYykv8RXD0uWyc/+A3y1mhRZlYuS7ygXPfFjiOwNy2Zq3EXxWRGF48niXHKv3UHgwrQJXx5petCZPZT++QxSwJEAVFvRkbuUVwWtPRXoWVPlAllcnPLcHnixNmUlGxzCHufFilO9WsKkLPnA4my/UZHhA+n+ZvCphqegidH3xVw73kgjoLDw0mARBKtpYXtzE7JerwfY2FGdmBkGAgL1Yf3y8BvQnCiXwBbmm8NVxn+araMr6VZO1GVRJxXNYW7r4icXxwQ/BI7M/1Xw4DwNrNu4qwiavpRK+7w4620imn671x1kD6H1o63Q5WFFMrmoI35RvocbKTR1tQKBgQDzWQ5LN3EZu7WHVXg4AATyOVQKIm2vBF68YXWawaimjfkTj0Y1jHC5HipRQtfDX56t8N18lcDA9gLkg/F7l6nSqBHhh7zWhvuPQEXtWqs4niSNMwc99Q0izcPNvUcx4batP/lQCbQKyYOwEKURmkPOEnpo6bFIOKPjFM5pLyMEEwKBgQDvYyvWoIbKpsMa0HedCAdL23jQ50etvfnd4eJrtmWXn8lUqGhUv5KJbiIN6itC4KXkmnv5Xjp4NEZW1fH2TKSwL09QQPKy5lB4w5qrX/EbkToLfcLNU59HHpxi7DcHdrDEbKSCy9RhP1A0T46+2NeF074yFWOwAn69ANbKA45nMwKBgQCOKjXmjWI+xWG8yZrtJF2/YOyO6yQm/ieWaF17Zq3vd7vOyIIc4IouK8hPJvzEQAWE2tWaZiZw1IhGFisqqCTnU5b2qgURU1R9kPAJRVIIRqNV9jzB3nqpHYrJlE2Wf6XoOxqcvr53GtkbL+4vhW8dYcAvsG8IoUZlcI9R9d7ADwKBgQC+kpeatI66E8ostZsTswmD9UOYIxboFN4vKp1DHKCB9Z2kvLDaDuyMZdXMeAhapFbMx8M8QSyQ9ySsCoQmjNtquy8L97h+fWXAzg96sNVUGeg4r7R+Gz0otBDRm7UvRujwZoEM81Gu3WVvT4qXGi9xhaDbZDXJMCNPObTEe9JJCwKBgEkX13x2IES9H92bkY6gaLpFF9JK6izrRnYqfvvcMPjRErHfaNsZL4ndXuyej8FSKNtP0FeXfEMqvbHeZ3qCr8kH17KXklUL8TIe4Q/Y/ROOmqU1mhbQoazFMCh86lOcOrfKy5qIdRKpeec0pGAyEcAt9hm2/H+QeiayvGhOoU4t
    appPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA445pdLpJZyLScT1vjcOBUp5xbFWDP/8HN4hwrN6PzjSyt2RdVX0h75Z1VpeOttWSHRCKgieRJjB0JLZcahkUfGGTE9AHSxG+wpokMz4dFZqkYy+kvLjGx2rIsH2WogUqI7OCEm6lD5f4l4/DSARdpDyfFYXVbs9QFe9aNVRSIRigAc5tDC05PaRCk8iqpHrws4FtZoZ1Boy6AW50fTRlO431UvnPBCPPri8gP3/PDArcVuYKAg2ymwoLRiimkT3DvAIdi5UjNrh1BB6YW3Wvje6IEQ6pNMFPuHn6wBCe3BEWfj1Ta9+A8u8Zg4ExxUalBXORfJDWOrvUIBhh9id0yQIDAQAB
    aliPayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhm7qe+2DJkr7WNPj2uC5bZKA96wo7gN8ON4bw1Nd0gcw8lC0DI5kUm3/i8A4FETR/Eqdit1tj9vrtgw8qpF/e+xoWOMM2L62SsupbXik/0jUnuM/7PlHWb9tMSoko4cds221YzmQwtMQSPJ3PVoTDwtCvIvpuq2mE6Drljoe6F9ZepBzmbABcDPySjvwNjo+qOntaXfAyr9LxeJY7TCVtf+Wh8JkBb495yEODxhHqMTvRFc48++AlcTCv8V0WTdmDs5H9jcbjrVXf/yM57HEhBwb/fJHGAkSi78Izy0CAty+I6h7Z/N0ES3dsrF84ho1sYsybZaQXK5T+uNmoPP3eQIDAQAB
    aesKey: Nb/7FghMcOhOw07gw6udyA==
    format: json
    charSet: utf-8
    signType: RSA2
    timeoutExpress: 30m
    notifyUrl: /pay/aliPay/notify.do
    returnUrl: /pay/aliPay/return.do
server:
  context-path: /novel
  port: 8080
  error:
    path: /error
  session:
    timeout: 2000
  tomcat:
    max-threads: 20000
    uri-encoding: utf-8
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.potato369.novel.basic.dataobject
management:
  security:
    enabled: false
  port: 9080
  context-path: /monitor
info:
  app:
    name: development-novel-spring-boot-actuator
    version: 1.0.0
security:
  user:
    name: admin
    password: wy1wj2yj3!@#
  basic:
    enabled: false
    path: /**
endpoints: 
  enabled: true