spring:
  profiles:
    active: dev
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: false
    checkTemplateLocation: true
    content-type: text/html
    exposeRequestAttributes: false
    exposeSessionAttributes: false
    exposeSpringMacroHelpers: false
    prefer-file-system-access: true
    suffix: .ftl
    charset: UTF-8
    template-loader-path: classpath:/templates/
weChat:
  pay:
    appId: wxfb0967015f2c8735
    mchId: 1539515591
    mchKey: 9dc8133c841faf945fd5844823755a34
    appSecret: 9dc8133c841faf945fd5844823755a34
    notifyUrl: /pay/notify
server:
  context-path: /novel
  port: 8080
  error:
    path: /error
  session:
    timeout: 2000
  tomcat:
    max-threads: 20000
    uri-encoding: utf-8
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.potato369.novel.basic.dataobject
management:
  security:
    enabled: false
  port: 9080
  context-path: /monitor
info:
  app:
    name: development-novel-spring-boot-actuator
    version: 1.0.0
security:
  user:
    name: admin
    password: wy1wj2yj3!@#
  basic:
    enabled: false
    path: /**
endpoints:
  enabled: true