spring:
  profiles:
    active: prod
#  jackson:
#    default-property-inclusion: non_null
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: false
    checkTemplateLocation: true
    content-type: text/html
    exposeRequestAttributes: false
    exposeSessionAttributes: false
    exposeSpringMacroHelpers: false
    prefer-file-system-access: true
    suffix: .ftl
    charset: UTF-8
    template-loader-path: classpath:/templates/
weChat: 
  mp:
    appId: wx53762126dcb961f9                     #土豆互联公众号AppId
    appSecret: 15b6fcb9cd933a561733a83e708f040a   #土豆互联公众号AppSecret
    token: potato369token
    aesKey: 8XSi84XgQJ1NE2Hh01FIzJxRVxUq7Eg4s8joHU2nq62
    templateId:
      orderStatus: l8ZgiVk7Cb3art8XjHtsyv6uPrpooT37ycS37EXywLM
      orderSuccess: Z_y_ovpCRyU0eBrikdJL9_VsehJA_AouU21L61k8vgc
      orderCancel: iGR0BRPe927iVHHFlW9sY-T33S9_EI-YcrY5EMnd4Rg
      paySuccess: oFx8eJFfs8VC_x58KflhSRcsLBgxCp0y10fwRJN9vRc
      sellerLoginSuccess: II0W0VUYbnpvHwNPsJuNsbuQYfV1F4ndhmTogiakR2o
  pay:
    appId: wx53762126dcb961f9
    mchId: 1453416602
    mchKey: c6b8341c4d274189bee934112a369212
    subAppId:
    subMchId:
    notifyUrl: /pay/notify
  open:
    appId: wx3c2ae24f69ea4121
    appSecret: 0a355cb0843b9b21f9c079f2ca7a72e5
xfYun: 
  appId: 5c0f3f67
  apiKey: b727bcf8859657dcd191c885935c4569
  host: api.xfyun.cn
  path: /v1/service/v1/tts
  method: POST
  auf: audio/L16;rate=16000
  aue: lame
  voiceName: xiaoyan
  speed: 30
  volume: 50
  pitch: 50
  engineType: intp65
  textType: text
server:
  context-path: /app
  port: 8980
  error:
    path: /error
  session:
    timeout: 2000
  tomcat:
   max-threads: 20000
   uri-encoding: utf-8
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.potato369.novel.basic.dataobject
management:
  security:
    enabled: false          #关掉安全认证
  port: 9080                #管理端口调整成9080
  context-path: /monitor    #actuator的访问路径
info:
  app:
    name: development-novel-spring-boot-actuator
    version: 1.0.0
security:
  user:
    name: admin
    password: wy1wj2yj3!@#
  basic:
    enabled: false
    path: /**
endpoints:
  enabled: true
