spring:
  datasource:
    druid:
      async-init: true
      url: jdbc:mysql://127.0.0.1:3306/novel_tmp?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&useOldAliasMetadataBehavior=true&serverTimezone=GMT%2B8
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: MyNewPassword4!@#
      keep-alive: true
      initial-size: 1
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-log-stats-millis: 300000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat, wall, log4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      reset-stat-enable: true
      stat-view-servlet:
        reset-enable: false
        login-username: admin
        login-password: wy1wj2yj3!@#
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  redis:
    host: 127.0.0.1
    port: 6379
    password: foobared123!@#
logging:
  level:
    org.springframework.web: debug
    com.potato369.novel.basic: debug
    com.potato369.novel.app.web: debug
    com.alibaba.druid: debug
    com.potato369.novel.basic.dataobject.mapper: debug
projectUrl: 
  projectName: /novel
  domainUrl: http://potato369.mynatapp.cc
  weChatMpAuthorizeUrl: /wechat/authorize
  weChatMpAuthorizeUrlUserInfo: /wechat/userInfo
  weChatOpenAuthorizeUrl: /wechat/qrAuthorize
  weChatOpenAuthorizeUrlUserInfo: /wechat/qrUserInfo
  loginUrl: /seller/login
  logoutUrl: /seller/logout
  errorUrl: /error
  successUrl: /success
  mp3FilePath: D:/Program/Resources/mp3
  uploadFilePath: D:/Program/Resources
  coverImgFilePath: D:/Program/Resources/epbu2
  resUrl: http://172.16.101.59:9000
weChat:
  pay:
    keyPath: D:\Users\wangyanjun\workspace\novel\src\main\resources\cert\open.p12