spring:
  datasource:
    druid:
      async-init: true
      url: jdbc:mysql://127.0.0.1:3306/novel_tmp?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&useOldAliasMetadataBehavior=true&serverTimezone=GMT%2B8
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: MyNewPassword4!
      keep-alive: true
      initial-size: 3
      min-idle: 15
      max-active: 60
      max-wait: 60000
      time-between-log-stats-millis: 300000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 60
      filters: stat, wall, log4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      reset-stat-enable: true
      stat-view-servlet:
        reset-enable: false
        login-username: admin
        login-password: wy1wj2yj3!@#
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    generate-ddl: false
  redis:
    host: 127.0.0.1
    port: 6379
    password: foobared123!@#
logging:
  level:
    org.springframework.web: error
    com.potato369.novel.basic: error
    com.potato369.novel.app.web: error
    com.alibaba.druid: error
    com.potato369.novel.basic.dataobject.mapper: error
    com.github.binarywang: error
projectUrl: 
  projectName: /app
  domainUrl: https://www.potato369.com
  weChatMpAuthorizeUrl: /wechat/authorize
  weChatMpAuthorizeUrlUserInfo: /wechat/userInfo
  weChatOpenAuthorizeUrl: /wechat/qrAuthorize
  weChatOpenAuthorizeUrlUserInfo: /wechat/qrUserInfo
  loginUrl: /novel/login
  logoutUrl: /novel/logout
  errorUrl: /error
  successUrl: /success
  mp3FilePath: /ebookData/upgrade_file/http/Resources/mp3
  coverImgFilePath: /ebookData/upgrade_file/http/Resources/img
  uploadFilePath: /ebookData/upgrade_file/http/Resources/epub
  resUrl: http://www.potato369.com:8000
weChat: 
  pay:
    keyPath: /var/local/wechatPayKeyFilePath/cert/h5.p12