spring:
  datasource:
    #################################################################################### Druid连接池的配置信息 ####################################################################
    druid:
      async-init: true                                        #有initialSize数量较多时，打开会加快应用启动时间
      url: jdbc:mysql://127.0.0.1:3306/novel_tmp?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&useOldAliasMetadataBehavior=true&serverTimezone=GMT%2B8 #数据库连接URL
      driver-class-name: com.mysql.jdbc.Driver                #数据库连接驱动类名称
      username: root                                          #数据库连接用户名
      password: 123456                                        #数据库连接密码
      keep-alive: true                                        #保持连接状态
      initial-size: 10                                        #数据库初始化连接大小
      min-idle: 10                                            #数据库最小连接池数量
      max-active: 40                                          #数据库最大连接池数量
      max-wait: 60000                                         #获取连接时最大等待时间，单位毫秒
      time-between-log-stats-millis: 300000                   #DruidDataSource有一个属性timeBetweenLogStatsMillis，配置timeBetweenLogStatsMillis>0之后，DruidDataSource会定期把监控数据输出到日志中
      time-between-eviction-runs-millis: 60000                #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000                  #配置一个连接在池中最小生存的时间，单位是毫秒
      validation-query: SELECT 1 FROM DUAL                    #测试数据库连接SQL
      test-while-idle: true                                   #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
      test-on-borrow: false                                   #获取连接时执行检测，建议关闭，影响性能
      test-on-return: false                                   #归还连接时执行检测，建议关闭，影响性能
      pool-prepared-statements: false                         #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
      max-pool-prepared-statement-per-connection-size: 40     #开启poolPreparedStatements后生效
      filters: stat,  wall, log4j                             #配置扩展插件，常用的插件有=>stat：监控统计，log4j：打印log4j日志，wall：防御sql注入
      connection-properties: 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000'  #通过connectProperties属性来打开mergeSql功能;慢SQL记录
      reset-stat-enable: true                                 #可以重置数据
      stat-view-servlet:                                      #配置 Druid 监控信息显示页面，Druid内置提供了一个StatViewServlet用于展示Druid的统计信息，这个StatViewServlet的用途包括：1、提供监控信息展示的html页面 2、提供监控信息的JSON API，注意：使用StatViewServlet，建议使用druid 0.2.6以上版本。
        reset-enable: false                                   #允许清空统计数据
        login-username: admin                                 #为Druid监控配置访问监控信息有访问权限的用户名
        login-password: wy1wj2yj3!@#                          #为Druid监控配置访问监控信息有访问权限的密码
    #################################################################################### Druid连接池的配置信息 ####################################################################
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  redis:
    host: 127.0.0.1
    port: 6379
    password: foobared123!@#
logging:
  level:
    org.springframework.web: info
    com.potato369.novel: info
    com.potato369.novel.crawler: info
    com.potato369.novel.basic: info
    com.alibaba.druid: info
    com.potato369.novel.basic.dataobject.mapper: trace
projectUrl:   
  projectName: /novel
  domainUrl: http://potato369.mynatapp.cc
  weChatMpAuthorizeUrl: /wechat/authorize
  weChatMpAuthorizeUrlUserInfo: /wechat/userInfo
  weChatOpenAuthorizeUrl: /wechat/qrAuthorize
  weChatOpenAuthorizeUrlUserInfo: /wechat/qrUserInfo
  loginUrl: /novel/login
  logoutUrl: /novel/logout
  errorUrl: /error
  successUrl: /success
  mp3FilePath: /ebookData/upgrade_file/http/Resources/mp3
  coverImgFilePath: /ebookData/upgrade_file/http/Resources/img
  uploadFilePath: /ebookData/upgrade_file/http/Resources/epub
  resUrl: http://192.168.1.172:9000
weChat: 
  ##mp:
   ##appId: wxe6b15040e8fe0a5d                   #测试号AppId
   ##appSecret: 747700f306a528059fb4aa73cb917340 #测试号AppSecret
  pay:
    keyPath: /var/local/wechatPayKeyFilePath/cert/h5.p12
management:
  security:
    enabled: false          #关掉安全认证
  port: 8080                #管理端口调整成8080
  context-path: /monitor    #actuator的访问路径
info:
  app:
    name: test-novel-spring-boot-actuator
    version: 1.0.0
security:
  user:
    name: admin
    password: wy1wj2yj3!@#
  basic:
    enabled: false
    path: /**
endpoints: 
  enabled: true
seimi:
  crawler:
    enabled: true
    names: 88dush2
    ##names: 88dush1,88dush2,88dush3,88dush4,88dush5,88dush6,88dush7,88dush8,88dush9
    ##names: dindian,biquyun,23us,sbiquge,gxwztv,00ksw,xbiquge,xbxwx,bxwx,zhuishushenqi,88dush  
  